mode = "dark"

accent = "#dc896c"
selection = "#49291f"
muted = "#876a61"

background = "#100301"
dark_background = "#0c0201"
darker_background = "#080201"
lighter_background = "#200e09"

foreground = "#f2dcd5"
dark_foreground = "#9c8a84"
light_foreground = "#dcc5be"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(dc896cee) rgba(71add0ee) 45deg"
hyprland_inactive_border = "rgba(876a61aa)"

red = "#ec8274"
yellow = "#eec058"
orange = "#f59e5b"
green = "#97c06e"
cyan = "#44cfcc"
blue = "#5fb4ed"
magenta = "#e28abd"
brown = "#865634"

bright_red = "#f8a092"
bright_yellow = "#ffd988"
bright_green = "#b2d491"
bright_cyan = "#7de2e0"
bright_blue = "#86c9f8"
bright_magenta = "#f1a7d0"
