mode = "light"

accent = "#807048"
selection = "#ded9c9"
muted = "#807d72"

background = "#f9f7ee"
dark_background = "#efede2"
darker_background = "#e2e0d4"
lighter_background = "#e7e5d8"

foreground = "#302e23"
dark_foreground = "#676355"
light_foreground = "#504d42"
bright_foreground = "#18160d"

hyprland_active_border = "rgba(807048ee) rgba(a3585aee) 45deg"
hyprland_inactive_border = "rgba(807d72aa)"

red = "#9e4d4b"
yellow = "#8e6c10"
orange = "#9d5a29"
green = "#587b3c"
cyan = "#057f7d"
blue = "#296996"
magenta = "#924f76"
brown = "#774826"

bright_red = "#8c3a3a"
bright_yellow = "#775804"
bright_green = "#446725"
bright_cyan = "#016967"
bright_blue = "#0e5885"
bright_magenta = "#803d66"
