mode = "dark"

accent = "#cb8e56"
selection = "#442d1a"
muted = "#826d61"

background = "#100703"
dark_background = "#0c0502"
darker_background = "#080402"
lighter_background = "#20140d"

foreground = "#eeded5"
dark_foreground = "#9a8c85"
light_foreground = "#d8c7bd"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(cb8e56ee) rgba(a8a96bee) 45deg"
hyprland_inactive_border = "rgba(826d61aa)"

red = "#dc8b87"
yellow = "#f6ba7d"
orange = "#eda17f"
green = "#acb979"
cyan = "#73c9c5"
blue = "#7ab2db"
magenta = "#d593b8"
brown = "#865634"

bright_red = "#eba6a1"
bright_yellow = "#ffd6ad"
bright_green = "#c3ce9a"
bright_cyan = "#99ddd9"
bright_blue = "#99c7ea"
bright_magenta = "#e5aecc"
