mode = "dark"

accent = "#fca237"
selection = "#563612"
muted = "#816e5c"

background = "#160c04"
dark_background = "#110903"
darker_background = "#0b0602"
lighter_background = "#261a0f"

foreground = "#edded2"
dark_foreground = "#9b8e84"
light_foreground = "#d7c7ba"
bright_foreground = "#fcf6f0"

hyprland_active_border = "rgba(fca237ee) rgba(56a9fdee) 45deg"
hyprland_inactive_border = "rgba(816e5caa)"

red = "#ec817a"
yellow = "#ffb762"
orange = "#fa9a6a"
green = "#98c06d"
cyan = "#43ced0"
blue = "#62b0fe"
magenta = "#e28abd"
brown = "#865634"

bright_red = "#f89f97"
bright_yellow = "#ffd6aa"
bright_green = "#b2d491"
bright_cyan = "#7ce1e3"
bright_blue = "#91c6fd"
bright_magenta = "#f1a7d1"
