mode = "dark"

accent = "#67acf7"
selection = "#203c59"
muted = "#607488"

background = "#05101b"
dark_background = "#040c14"
darker_background = "#03080e"
lighter_background = "#111f2c"

foreground = "#d5e3f2"
dark_foreground = "#8693a0"
light_foreground = "#bdcddc"
bright_foreground = "#f2f8fd"

hyprland_active_border = "rgba(67acf7ee) rgba(70b1b9ee) 45deg"
hyprland_inactive_border = "rgba(607488aa)"

red = "#ec817d"
yellow = "#edc158"
orange = "#f69e5f"
green = "#84c575"
cyan = "#21cfda"
blue = "#65b0f9"
magenta = "#e089c7"
brown = "#865634"

bright_red = "#f99f9a"
bright_yellow = "#fed988"
bright_green = "#a3d997"
bright_cyan = "#6fe2eb"
bright_blue = "#8fc6fd"
bright_magenta = "#efa6d8"
