mode = "dark"

accent = "#cf967a"
selection = "#402d24"
muted = "#7d6e69"

background = "#080403"
dark_background = "#060302"
darker_background = "#040202"
lighter_background = "#16100e"

foreground = "#eadeda"
dark_foreground = "#948b88"
light_foreground = "#d4c7c3"
bright_foreground = "#fdf5f2"

hyprland_active_border = "rgba(cf967aee) rgba(65b5aeee) 45deg"
hyprland_inactive_border = "rgba(7d6e69aa)"

red = "#dc8d7d"
yellow = "#e4c379"
orange = "#e6a674"
green = "#a4bb7f"
cyan = "#75c9c0"
blue = "#7bb1dc"
magenta = "#d494bb"
brown = "#865634"

bright_red = "#eaa89a"
bright_yellow = "#f6db9f"
bright_green = "#bcd09e"
bright_cyan = "#9addd5"
bright_blue = "#9ac7ea"
bright_magenta = "#e4aecf"
