mode = "light"

accent = "#4b708c"
selection = "#c6d5df"
muted = "#727a80"

background = "#e9f1f7"
dark_background = "#dde8ee"
darker_background = "#d0dbe2"
lighter_background = "#d4e0e8"

foreground = "#282f34"
dark_foreground = "#58656e"
light_foreground = "#474e53"
bright_foreground = "#11171b"

hyprland_active_border = "rgba(4b708cee) rgba(ad5151ee) 45deg"
hyprland_inactive_border = "rgba(727a80aa)"

red = "#a24a44"
yellow = "#866827"
orange = "#985929"
green = "#567540"
cyan = "#12797c"
blue = "#346890"
magenta = "#8c5476"
brown = "#774826"

bright_red = "#903733"
bright_yellow = "#735506"
bright_green = "#43622c"
bright_cyan = "#006568"
bright_blue = "#1f577f"
bright_magenta = "#7b4265"
