mode = "dark"

accent = "#f1b6e6"
selection = "#583f53"
muted = "#826d7d"

background = "#1c111a"
dark_background = "#150d14"
darker_background = "#0e090d"
lighter_background = "#2d1f2a"

foreground = "#ecdce7"
dark_foreground = "#9d8f99"
light_foreground = "#d6c5d1"
bright_foreground = "#fbf4f9"

hyprland_active_border = "rgba(f1b6e6ee) rgba(8ea3dbee) 45deg"
hyprland_inactive_border = "rgba(826d7daa)"

red = "#e4877d"
yellow = "#e7c36a"
orange = "#eea269"
green = "#8dc27c"
cyan = "#4dcdd0"
blue = "#7facf0"
magenta = "#d58fca"
brown = "#885836"

bright_red = "#f2a39a"
bright_yellow = "#f9db94"
bright_green = "#aad69c"
bright_cyan = "#81e0e2"
bright_blue = "#9dc3fc"
bright_magenta = "#e5aadb"
