mode = "light"

accent = "#6f7022"
selection = "#d4d5ba"
muted = "#787b69"

background = "#f0f2e5"
dark_background = "#e6e8d9"
darker_background = "#d8dbcb"
lighter_background = "#dde0ce"

foreground = "#2d301e"
dark_foreground = "#626554"
light_foreground = "#4c4f3e"
bright_foreground = "#16170a"

hyprland_active_border = "rgba(6f7022ee) rgba(477e6cee) 45deg"
hyprland_inactive_border = "rgba(787b69aa)"

red = "#9e4e45"
yellow = "#8d680a"
orange = "#9b5925"
green = "#697328"
cyan = "#0e7a7a"
blue = "#2c6896"
magenta = "#924f76"
brown = "#774826"

bright_red = "#8c3b34"
bright_yellow = "#755500"
bright_green = "#57600a"
bright_cyan = "#0d6565"
bright_blue = "#145786"
bright_magenta = "#803d65"
