mode = "light"

accent = "#c33742"
selection = "#f1c1c3"
muted = "#8b706f"

background = "#fee8e7"
dark_background = "#fbdbda"
darker_background = "#f0cdcc"
lighter_background = "#f7d1d0"

foreground = "#402625"
dark_foreground = "#745d5c"
light_foreground = "#5f4645"
bright_foreground = "#221010"

hyprland_active_border = "rgba(c33742ee) rgba(33824eee) 45deg"
hyprland_inactive_border = "rgba(8b706faa)"

red = "#b83032"
yellow = "#876703"
orange = "#a25200"
green = "#2f7a33"
cyan = "#117876"
blue = "#066a9e"
magenta = "#9c447b"
brown = "#774826"

bright_red = "#a50f1d"
bright_yellow = "#6f5404"
bright_green = "#11661b"
bright_cyan = "#086260"
bright_blue = "#085885"
bright_magenta = "#8a306a"
