mode = "light"

accent = "#955a8b"
selection = "#e8d1e2"
muted = "#8a7685"

background = "#fff2fb"
dark_background = "#f9e6f4"
darker_background = "#edd9e7"
lighter_background = "#f3dded"

foreground = "#392735"
dark_foreground = "#6f5d6a"
light_foreground = "#594754"
bright_foreground = "#1e111b"

hyprland_active_border = "rgba(955a8bee) rgba(5a6fa8ee) 45deg"
hyprland_inactive_border = "rgba(8a7685aa)"

red = "#a54740"
yellow = "#8b6b04"
orange = "#9e5817"
green = "#477d34"
cyan = "#077d7f"
blue = "#3662a6"
magenta = "#914b87"
brown = "#774826"

bright_red = "#93332d"
bright_yellow = "#745908"
bright_green = "#326a1c"
bright_cyan = "#04686a"
bright_blue = "#225095"
bright_magenta = "#803876"
