mode = "light"

accent = "#9f567a"
selection = "#e9d0dc"
muted = "#8f757f"

background = "#fef2f7"
dark_background = "#fde4ee"
darker_background = "#f4d5e1"
lighter_background = "#fbd9e6"

foreground = "#3e252f"
dark_foreground = "#725c65"
light_foreground = "#5d454f"
bright_foreground = "#211017"

hyprland_active_border = "rgba(9f567aee) rgba(836e4bee) 45deg"
hyprland_inactive_border = "rgba(8f757faa)"

red = "#a54740"
yellow = "#8c6b04"
orange = "#9f5818"
green = "#537b2e"
cyan = "#0b7d7e"
blue = "#15699f"
magenta = "#994975"
brown = "#774826"

bright_red = "#93332d"
bright_yellow = "#755909"
bright_green = "#406813"
bright_cyan = "#086869"
bright_blue = "#005789"
bright_magenta = "#873664"
