mode = "light"

accent = "#8255c2"
selection = "#cdcfee"
muted = "#667b87"

background = "#e2f2fb"
dark_background = "#d6e8f4"
darker_background = "#c8dbe8"
lighter_background = "#cbe1ee"

foreground = "#1c313d"
dark_foreground = "#536672"
light_foreground = "#3d505c"
bright_foreground = "#081821"

hyprland_active_border = "rgba(8255c2ee) rgba(9c6307ee) 45deg"
hyprland_inactive_border = "rgba(667b87aa)"

red = "#9c2834"
yellow = "#896600"
orange = "#984a05"
green = "#1a7b53"
cyan = "#0b7791"
blue = "#3853b0"
magenta = "#83429d"
brown = "#774826"

bright_red = "#8a0822"
bright_yellow = "#725503"
bright_green = "#026742"
bright_cyan = "#006277"
bright_blue = "#28409f"
bright_magenta = "#722e8c"
