mode = "dark"

accent = "#dcd5d0"
selection = "#4b4643"
muted = "#797067"

background = "#120f0c"
dark_background = "#0e0b09"
darker_background = "#090806"
lighter_background = "#211d1a"

foreground = "#e7e0d9"
dark_foreground = "#96918b"
light_foreground = "#d1c9c1"
bright_foreground = "#fcf6f0"

hyprland_active_border = "rgba(dcd5d0ee) rgba(65b3bfee) 45deg"
hyprland_inactive_border = "rgba(797067aa)"

red = "#df8071"
yellow = "#f8c885"
orange = "#efa373"
green = "#98c5a0"
cyan = "#9cd7da"
blue = "#79b5cc"
magenta = "#c8a4c3"
brown = "#865634"

bright_red = "#ec9c8f"
bright_yellow = "#ffe3be"
bright_green = "#b4d9bb"
bright_cyan = "#bcecee"
bright_blue = "#99cadd"
bright_magenta = "#dbbdd7"
