mode = "dark"

accent = "#ded7c4"
selection = "#4e4b43"
muted = "#767367"

background = "#161511"
dark_background = "#11100d"
darker_background = "#0b0b09"
lighter_background = "#25241f"

foreground = "#e3e1d8"
dark_foreground = "#95938c"
light_foreground = "#cdcbc0"
bright_foreground = "#f8f7ef"

hyprland_active_border = "rgba(ded7c4ee) rgba(d78e8eee) 45deg"
hyprland_inactive_border = "rgba(767367aa)"

red = "#dc8b87"
yellow = "#e5c379"
orange = "#e8a477"
green = "#9bbe81"
cyan = "#6ccac7"
blue = "#78b2df"
magenta = "#d693b9"
brown = "#885836"

bright_red = "#eba6a2"
bright_yellow = "#f7dba0"
bright_green = "#b5d2a0"
bright_cyan = "#94dedb"
bright_blue = "#98c7ed"
bright_magenta = "#e6adcd"
