mode = "light"

accent = "#4e61d9"
selection = "#cad1f4"
muted = "#71788e"

background = "#edf1fc"
dark_background = "#dfe7fd"
darker_background = "#d0daf5"
lighter_background = "#d4defc"

foreground = "#262d42"
dark_foreground = "#5c6375"
light_foreground = "#454c61"
bright_foreground = "#111524"

hyprland_active_border = "rgba(4e61d9ee) rgba(8c6d09ee) 45deg"
hyprland_inactive_border = "rgba(71788eaa)"

red = "#983835"
yellow = "#87690c"
orange = "#96500c"
green = "#43784f"
cyan = "#0b7796"
blue = "#3155c0"
magenta = "#6c599e"
brown = "#774826"

bright_red = "#862323"
bright_yellow = "#725700"
bright_green = "#2e663c"
bright_cyan = "#04637e"
bright_blue = "#2141af"
bright_magenta = "#5c478d"
