mode = "light"

accent = "#936208"
selection = "#dfceb6"
muted = "#81756f"

background = "#f5ece7"
dark_background = "#ede1dc"
darker_background = "#e0d4ce"
lighter_background = "#e6d9d2"

foreground = "#362b26"
dark_foreground = "#6e6059"
light_foreground = "#564a45"
bright_foreground = "#1c1410"

hyprland_active_border = "rgba(936208ee) rgba(9f5b5eee) 45deg"
hyprland_inactive_border = "rgba(81756faa)"

red = "#ac3f41"
yellow = "#8e640c"
orange = "#a25219"
green = "#50761d"
cyan = "#0c7878"
blue = "#06699f"
magenta = "#99467f"
brown = "#774826"

bright_red = "#9a292f"
bright_yellow = "#755209"
bright_green = "#3e6300"
bright_cyan = "#076364"
bright_blue = "#075784"
bright_magenta = "#87326e"
