mode = "light"

accent = "#287d5d"
selection = "#c0dbd1"
muted = "#6e7f78"

background = "#ebf6f2"
dark_background = "#e0ece8"
darker_background = "#d2e0da"
lighter_background = "#d6e5df"

foreground = "#21322c"
dark_foreground = "#576861"
light_foreground = "#41514b"
bright_foreground = "#0c1915"

hyprland_active_border = "rgba(287d5dee) rgba(7c7331ee) 45deg"
hyprland_inactive_border = "rgba(6e7f78aa)"

red = "#a54741"
yellow = "#7f6f05"
orange = "#9b5a09"
green = "#277d47"
cyan = "#137b7e"
blue = "#1f67a1"
magenta = "#954a7e"
brown = "#774826"

bright_red = "#93332f"
bright_yellow = "#6a5c09"
bright_green = "#096a35"
bright_cyan = "#0f6669"
bright_blue = "#05558e"
bright_magenta = "#84376d"
