mode = "dark"

accent = "#efb547"
selection = "#553d17"
muted = "#7f6e59"

background = "#190f04"
dark_background = "#130b03"
darker_background = "#0d0802"
lighter_background = "#291e0f"

foreground = "#ecdfd0"
dark_foreground = "#9c9082"
light_foreground = "#d6c8b8"
bright_foreground = "#fbf6f0"

hyprland_active_border = "rgba(efb547ee) rgba(ec836dee) 45deg"
hyprland_inactive_border = "rgba(7f6e59aa)"

red = "#ec8275"
yellow = "#f8bc50"
orange = "#f99c5d"
green = "#9fbe6b"
cyan = "#4ccecc"
blue = "#66b3ec"
magenta = "#e28abb"
brown = "#865634"

bright_red = "#f99f93"
bright_yellow = "#ffd89a"
bright_green = "#b8d38f"
bright_cyan = "#80e1df"
bright_blue = "#8bc9f8"
bright_magenta = "#f1a7ce"
