mode = "light"

accent = "#6e7401"
selection = "#d3d9b4"
muted = "#767e6a"

background = "#eff6e6"
dark_background = "#e5ecda"
darker_background = "#d7dfcc"
lighter_background = "#dce4d0"

foreground = "#2a311e"
dark_foreground = "#5f6654"
light_foreground = "#49503e"
bright_foreground = "#13180a"

hyprland_active_border = "rgba(6e7401ee) rgba(b3501aee) 45deg"
hyprland_inactive_border = "rgba(767e6aaa)"

red = "#ac4231"
yellow = "#8d6a00"
orange = "#a15700"
green = "#67760b"
cyan = "#037c7c"
blue = "#0967a8"
magenta = "#9b447f"
brown = "#774826"

bright_red = "#9a2c1d"
bright_yellow = "#755700"
bright_green = "#566206"
bright_cyan = "#006768"
bright_blue = "#05568e"
bright_magenta = "#89306e"
