mode = "light"

accent = "#a85334"
selection = "#eac9be"
muted = "#8c726a"

background = "#fceae5"
dark_background = "#f8ded6"
darker_background = "#ecd0c8"
lighter_background = "#f3d5cc"

foreground = "#3f271f"
dark_foreground = "#735e57"
light_foreground = "#5e4740"
bright_foreground = "#22110c"

hyprland_active_border = "rgba(a85334ee) rgba(36799eee) 45deg"
hyprland_inactive_border = "rgba(8c726aaa)"

red = "#ac4136"
yellow = "#896707"
orange = "#9f5507"
green = "#4f7718"
cyan = "#107877"
blue = "#006a9e"
magenta = "#9c447b"
brown = "#774826"

bright_red = "#9a2b22"
bright_yellow = "#715405"
bright_green = "#3e6300"
bright_cyan = "#0a6362"
bright_blue = "#025884"
bright_magenta = "#8a306a"
