mode = "dark"

accent = "#1cccce"
selection = "#083f44"
muted = "#577782"

background = "#00080e"
dark_background = "#00060b"
darker_background = "#000407"
lighter_background = "#01171e"

foreground = "#cfe6ee"
dark_foreground = "#809299"
light_foreground = "#b7cfd8"
bright_foreground = "#f0f8fc"

hyprland_active_border = "rgba(1cccceee) rgba(aca954ee) 45deg"
hyprland_inactive_border = "rgba(577782aa)"

red = "#ec817f"
yellow = "#d9ca5c"
orange = "#f2a156"
green = "#89c471"
cyan = "#07d0d6"
blue = "#64b1f7"
magenta = "#e089c7"
brown = "#865634"

bright_red = "#f99f9c"
bright_yellow = "#ece18b"
bright_green = "#a7d894"
bright_cyan = "#3ce7ed"
bright_blue = "#8cc7ff"
bright_magenta = "#efa6d8"
