mode = "light"

accent = "#4c7a38"
selection = "#cad9c1"
muted = "#737d6c"

background = "#edf4e8"
dark_background = "#e2eadd"
darker_background = "#d5decf"
lighter_background = "#d9e3d3"

foreground = "#283122"
dark_foreground = "#5d6757"
light_foreground = "#475041"
bright_foreground = "#12180d"

hyprland_active_border = "rgba(4c7a38ee) rgba(94663fee) 45deg"
hyprland_inactive_border = "rgba(737d6caa)"

red = "#9e4d49"
yellow = "#976418"
orange = "#9e5730"
green = "#4b7a3b"
cyan = "#007a7b"
blue = "#2e6799"
magenta = "#904f7b"
brown = "#774826"

bright_red = "#8c3a37"
bright_yellow = "#805101"
bright_green = "#366624"
bright_cyan = "#006566"
bright_blue = "#185688"
bright_magenta = "#7f3d6a"
