mode = "light"

accent = "#7a6c0c"
selection = "#d8d4af"
muted = "#7d7a62"

background = "#f3f1dd"
dark_background = "#eae7cf"
darker_background = "#dddac0"
lighter_background = "#e2dfc3"

foreground = "#322f16"
dark_foreground = "#666451"
light_foreground = "#514e38"
bright_foreground = "#191606"

hyprland_active_border = "rgba(7a6c0cee) rgba(976159ee) 45deg"
hyprland_inactive_border = "rgba(7d7a62aa)"

red = "#a54741"
yellow = "#826b00"
orange = "#9b580f"
green = "#547729"
cyan = "#0d7a79"
blue = "#20689f"
magenta = "#974a79"
brown = "#774826"

bright_red = "#93332f"
bright_yellow = "#6c5904"
bright_green = "#41640b"
bright_cyan = "#096565"
bright_blue = "#06568c"
bright_magenta = "#863768"
