mode = "light"

accent = "#6c6793"
selection = "#d1d0e0"
muted = "#777680"

background = "#ededf6"
dark_background = "#e3e3ed"
darker_background = "#d6d5e1"
lighter_background = "#dbdae6"

foreground = "#2d2d35"
dark_foreground = "#62616f"
light_foreground = "#4d4c55"
bright_foreground = "#16151c"

hyprland_active_border = "rgba(6c6793ee) rgba(5e7c4bee) 45deg"
hyprland_inactive_border = "rgba(777680aa)"

red = "#9e4d48"
yellow = "#886602"
orange = "#995724"
green = "#517532"
cyan = "#01787d"
blue = "#4c5f9e"
magenta = "#924e79"
brown = "#774826"

bright_red = "#8c3b36"
bright_yellow = "#705508"
bright_green = "#3e621b"
bright_cyan = "#026368"
bright_blue = "#3b4e8d"
bright_magenta = "#803c68"
