mode = "dark"

accent = "#8d96e8"
selection = "#2b2e4f"
muted = "#6b708a"

background = "#050614"
dark_background = "#04050f"
darker_background = "#03030a"
lighter_background = "#111325"

foreground = "#dde0f4"
dark_foreground = "#8b8d9f"
light_foreground = "#c6c9de"
bright_foreground = "#f5f6fe"

hyprland_active_border = "rgba(8d96e8ee) rgba(c68bd3ee) 45deg"
hyprland_inactive_border = "rgba(6b708aaa)"

red = "#df7e86"
yellow = "#efcc83"
orange = "#f0a276"
green = "#8ac8a6"
cyan = "#7ccffe"
blue = "#7a97fb"
magenta = "#cf8fde"
brown = "#865634"

bright_red = "#ec9ba0"
bright_yellow = "#fee5b1"
bright_green = "#a9dcc0"
bright_cyan = "#b5e2fd"
bright_blue = "#98b0fc"
bright_magenta = "#e0abec"
