mode = "light"

accent = "#4e7900"
selection = "#c9d7ac"
muted = "#757b64"

background = "#ecf2dc"
dark_background = "#e2e9ce"
darker_background = "#d5dcc0"
lighter_background = "#d9e1c3"

foreground = "#2c3119"
dark_foreground = "#616653"
light_foreground = "#4b503a"
bright_foreground = "#141808"

hyprland_active_border = "rgba(4e7900ee) rgba(a35b45ee) 45deg"
hyprland_inactive_border = "rgba(757b64aa)"

red = "#ac4132"
yellow = "#896806"
orange = "#9f5501"
green = "#427a01"
cyan = "#117879"
blue = "#0469a1"
magenta = "#9a4582"
brown = "#774826"

bright_red = "#992c1d"
bright_yellow = "#715506"
bright_green = "#356500"
bright_cyan = "#0c6364"
bright_blue = "#055787"
bright_magenta = "#883171"
