mode = "dark"

accent = "#b48df4"
selection = "#332d4f"
muted = "#5f7583"

background = "#01080f"
dark_background = "#01060b"
darker_background = "#010408"
lighter_background = "#08171f"

foreground = "#d4e4ee"
dark_foreground = "#849099"
light_foreground = "#bcced8"
bright_foreground = "#f1f8fd"

hyprland_active_border = "rgba(b48df4ee) rgba(d49648ee) 45deg"
hyprland_inactive_border = "rgba(5f7583aa)"

red = "#e17174"
yellow = "#f5cb70"
orange = "#f59b62"
green = "#7bcba1"
cyan = "#67d5f5"
blue = "#7999f5"
magenta = "#cc8ee7"
brown = "#865634"

bright_red = "#ee8f8f"
bright_yellow = "#ffe5b0"
bright_green = "#9edebb"
bright_cyan = "#a2e7fe"
bright_blue = "#94b1fe"
bright_magenta = "#ddaaf4"
