mode = "dark"

accent = "#d96a7e"
selection = "#47212a"
muted = "#816a76"

background = "#0e0409"
dark_background = "#0b0307"
darker_background = "#070205"
lighter_background = "#1d1018"

foreground = "#eddce5"
dark_foreground = "#988a91"
light_foreground = "#d7c5ce"
bright_foreground = "#fcf4f8"

hyprland_active_border = "rgba(d96a7eee) rgba(58ba93ee) 45deg"
hyprland_inactive_border = "rgba(816a76aa)"

red = "#e07081"
yellow = "#efcc83"
orange = "#f29c6e"
green = "#67cfa0"
cyan = "#7ce0ca"
blue = "#79a9db"
magenta = "#e885bf"
brown = "#865634"

bright_red = "#ed8e9a"
bright_yellow = "#fee5b1"
bright_green = "#90e2ba"
bright_cyan = "#a4f4e1"
bright_blue = "#97bfe9"
bright_magenta = "#f6a3d2"
