mode = "light"

accent = "#0d7797"
selection = "#b1d9e7"
muted = "#647d89"

background = "#dff4fd"
dark_background = "#ceebf9"
darker_background = "#bfdeed"
lighter_background = "#c2e4f4"

foreground = "#16323e"
dark_foreground = "#526771"
light_foreground = "#39515c"
bright_foreground = "#061921"

hyprland_active_border = "rgba(0d7797ee) rgba(0b8189ee) 45deg"
hyprland_inactive_border = "rgba(647d89aa)"

red = "#ac403e"
yellow = "#866906"
orange = "#a05508"
green = "#3b7c23"
cyan = "#04666d"
blue = "#0b6c93"
magenta = "#9b4383"
brown = "#774826"

bright_red = "#9a2a2c"
bright_yellow = "#6f5708"
bright_green = "#266705"
bright_cyan = "#02545a"
bright_blue = "#005a7d"
bright_magenta = "#892f72"
