mode = "light"

accent = "#ba3877"
selection = "#dfccce"
muted = "#6e7e6b"

background = "#e9f6e6"
dark_background = "#deedda"
darker_background = "#d0e0cc"
lighter_background = "#d4e5d0"

foreground = "#243320"
dark_foreground = "#5a6857"
light_foreground = "#435240"
bright_foreground = "#0f190c"

hyprland_active_border = "rgba(ba3877ee) rgba(238831ee) 45deg"
hyprland_inactive_border = "rgba(6e7e6baa)"

red = "#9e1755"
yellow = "#7d6e07"
orange = "#9c4703"
green = "#088122"
cyan = "#0b5e4e"
blue = "#08724a"
magenta = "#9b3480"
brown = "#774826"

bright_red = "#870045"
bright_yellow = "#685c09"
bright_green = "#046b1b"
bright_cyan = "#074c3e"
bright_blue = "#005f3c"
bright_magenta = "#891b6f"
