mode = "dark"

accent = "#b3d78f"
selection = "#3f4d34"
muted = "#6c7768"

background = "#121811"
dark_background = "#0e120d"
darker_background = "#090c09"
lighter_background = "#21271f"

foreground = "#dce4d9"
dark_foreground = "#8f968d"
light_foreground = "#c4cec1"
bright_foreground = "#f4f8f2"

hyprland_active_border = "rgba(b3d78fee) rgba(a7ab56ee) 45deg"
hyprland_inactive_border = "rgba(6c7768aa)"

red = "#e4877e"
yellow = "#dbc86b"
orange = "#eba464"
green = "#9abf75"
cyan = "#53ccd1"
blue = "#6fb1ea"
magenta = "#db8ebe"
brown = "#885836"

bright_red = "#f2a39b"
bright_yellow = "#eedf95"
bright_green = "#b4d396"
bright_cyan = "#84e0e3"
bright_blue = "#91c7f6"
bright_magenta = "#eba9d1"
