mode = "light"

accent = "#9b5296"
selection = "#e5cee3"
muted = "#847783"

background = "#faf1f9"
dark_background = "#f1e6f0"
darker_background = "#e4d9e3"
lighter_background = "#eadde8"

foreground = "#352934"
dark_foreground = "#6b5f6a"
light_foreground = "#554953"
bright_foreground = "#1c121b"

hyprland_active_border = "rgba(9b5296ee) rgba(138282ee) 45deg"
hyprland_inactive_border = "rgba(847783aa)"

red = "#962e68"
yellow = "#866c02"
orange = "#a14622"
green = "#1f7e3f"
cyan = "#057c7f"
blue = "#1c5fad"
magenta = "#8044a0"
brown = "#774826"

bright_red = "#841557"
bright_yellow = "#705a05"
bright_green = "#086b30"
bright_cyan = "#00676a"
bright_blue = "#004d99"
bright_magenta = "#6f3090"
