mode = "dark"

accent = "#48cc93"
selection = "#14462e"
muted = "#587b68"

background = "#001207"
dark_background = "#000e05"
darker_background = "#000904"
lighter_background = "#042214"

foreground = "#d1e8da"
dark_foreground = "#82978a"
light_foreground = "#bbd1c4"
bright_foreground = "#f1f9f4"

hyprland_active_border = "rgba(48cc93ee) rgba(b6a36dee) 45deg"
hyprland_inactive_border = "rgba(587b68aa)"

red = "#df7f78"
yellow = "#e5d183"
orange = "#eba66c"
green = "#4ed589"
cyan = "#6fe4bf"
blue = "#4eb9ad"
magenta = "#d29ccc"
brown = "#865634"

bright_red = "#ec9b94"
bright_yellow = "#f9e8a9"
bright_green = "#82e7a8"
bright_cyan = "#9cf7d7"
bright_blue = "#7accc1"
bright_magenta = "#e3b6de"
