mode = "dark"

accent = "#5cb5fc"
selection = "#1a3b59"
muted = "#56768c"

background = "#000c19"
dark_background = "#000913"
darker_background = "#00060d"
lighter_background = "#011b2b"

foreground = "#d0e5f3"
dark_foreground = "#8193a0"
light_foreground = "#b9cedc"
bright_foreground = "#f1f8fd"

hyprland_active_border = "rgba(5cb5fcee) rgba(c79a79ee) 45deg"
hyprland_inactive_border = "rgba(56768caa)"

red = "#ec8277"
yellow = "#fbb95e"
orange = "#f99b65"
green = "#85c574"
cyan = "#21d0d7"
blue = "#5eb1fe"
magenta = "#e089c7"
brown = "#865634"

bright_red = "#f99f95"
bright_yellow = "#fed7a5"
bright_green = "#a4d996"
bright_cyan = "#70e3e9"
bright_blue = "#8ec7ff"
bright_magenta = "#efa6d9"
