mode = "light"

accent = "#695cd2"
selection = "#d2cff5"
muted = "#77788f"

background = "#eff0ff"
dark_background = "#e5e5fc"
darker_background = "#d7d8f4"
lighter_background = "#dbdcfb"

foreground = "#2b2b41"
dark_foreground = "#616174"
light_foreground = "#4a4b60"
bright_foreground = "#141423"

hyprland_active_border = "rgba(695cd2ee) rgba(98578bee) 45deg"
hyprland_inactive_border = "rgba(77788faa)"

red = "#ac3f42"
yellow = "#8b690a"
orange = "#a25413"
green = "#3c7c23"
cyan = "#057980"
blue = "#4156c4"
magenta = "#994487"
brown = "#774826"

bright_red = "#9a2930"
bright_yellow = "#725609"
bright_green = "#266704"
bright_cyan = "#00656a"
bright_blue = "#3242b3"
bright_magenta = "#873076"
