mode = "dark"

accent = "#d89c74"
selection = "#4c3426"
muted = "#816d63"

background = "#160c08"
dark_background = "#110906"
darker_background = "#0b0604"
lighter_background = "#261b15"

foreground = "#edded6"
dark_foreground = "#9b8e88"
light_foreground = "#d7c7bf"
bright_foreground = "#fdf5f1"

hyprland_active_border = "rgba(d89c74ee) rgba(85aac4ee) 45deg"
hyprland_inactive_border = "rgba(816d63aa)"

red = "#dc8d7e"
yellow = "#e6c27a"
orange = "#e6a675"
green = "#9ebd81"
cyan = "#70c9c5"
blue = "#78b2dd"
magenta = "#d693b7"
brown = "#865634"

bright_red = "#eba89b"
bright_yellow = "#f7da9f"
bright_green = "#b7d2a0"
bright_cyan = "#96ddd9"
bright_blue = "#98c7eb"
bright_magenta = "#e6adcb"
