mode = "light"

accent = "#9d5d18"
selection = "#e7cdb8"
muted = "#887469"

background = "#fcede5"
dark_background = "#f4e2d9"
darker_background = "#e8d5cb"
lighter_background = "#eedace"

foreground = "#3b291f"
dark_foreground = "#725f54"
light_foreground = "#5b493f"
bright_foreground = "#20120b"

hyprland_active_border = "rgba(9d5d18ee) rgba(767631ee) 45deg"
hyprland_inactive_border = "rgba(887469aa)"

red = "#9e4d4a"
yellow = "#9a5f15"
orange = "#9f5431"
green = "#68732f"
cyan = "#007a77"
blue = "#2c6992"
magenta = "#915076"
brown = "#774826"

bright_red = "#8c3a39"
bright_yellow = "#834e00"
bright_green = "#545f14"
bright_cyan = "#016563"
bright_blue = "#125881"
bright_magenta = "#7f3e65"
