mode = "dark"

accent = "#c7f2f9"
selection = "#3d4a4f"
muted = "#6e717e"

background = "#07080d"
dark_background = "#05060a"
darker_background = "#040407"
lighter_background = "#15161c"

foreground = "#dee1eb"
dark_foreground = "#8c8f97"
light_foreground = "#c7cad5"
bright_foreground = "#f4f6fe"

hyprland_active_border = "rgba(c7f2f9ee) rgba(c290c7ee) 45deg"
hyprland_inactive_border = "rgba(6e717eaa)"

red = "#dc8b87"
yellow = "#e2c479"
orange = "#e7a576"
green = "#95c081"
cyan = "#62cbcb"
blue = "#77b1e5"
magenta = "#cf94c7"
brown = "#865634"

bright_red = "#eba6a1"
bright_yellow = "#f4dc9f"
bright_green = "#b0d4a0"
bright_cyan = "#8ddfde"
bright_blue = "#97c7f2"
bright_magenta = "#e0aed9"
