mode = "light"

accent = "#ae4d4d"
selection = "#ebc9c7"
muted = "#887371"

background = "#fcecea"
dark_background = "#f4e2df"
darker_background = "#e8d4d2"
lighter_background = "#eed9d6"

foreground = "#3b2826"
dark_foreground = "#725e5b"
light_foreground = "#5b4845"
bright_foreground = "#201210"

hyprland_active_border = "rgba(ae4d4dee) rgba(687855ee) 45deg"
hyprland_inactive_border = "rgba(887371aa)"

red = "#a54742"
yellow = "#8b6700"
orange = "#9e561a"
green = "#58762a"
cyan = "#0b7878"
blue = "#186a9a"
magenta = "#964b78"
brown = "#774826"

bright_red = "#933330"
bright_yellow = "#725402"
bright_green = "#45630d"
bright_cyan = "#086364"
bright_blue = "#055885"
bright_magenta = "#853867"
