mode = "dark"

accent = "#b4d6d4"
selection = "#354140"
muted = "#667575"

background = "#030707"
dark_background = "#020505"
darker_background = "#020404"
lighter_background = "#0e1414"

foreground = "#d8e4e4"
dark_foreground = "#879090"
light_foreground = "#c0cecd"
bright_foreground = "#f0f9f9"

hyprland_active_border = "rgba(b4d6d4ee) rgba(c29997ee) 45deg"
hyprland_inactive_border = "rgba(667575aa)"

red = "#d49089"
yellow = "#dfc488"
orange = "#dfa881"
green = "#9bbd8a"
cyan = "#77c7ca"
blue = "#83b0db"
magenta = "#cf97bb"
brown = "#865634"

bright_red = "#e3aaa3"
bright_yellow = "#f2dcaa"
bright_green = "#b5d2a7"
bright_cyan = "#9bdbdd"
bright_blue = "#a1c6ea"
bright_magenta = "#e0b1cf"
