mode = "light"

accent = "#ad4d66"
selection = "#ebcbd5"
muted = "#89757e"

background = "#fdeef4"
dark_background = "#f5e3eb"
darker_background = "#e8d5de"
lighter_background = "#eedae3"

foreground = "#3a2830"
dark_foreground = "#705d66"
light_foreground = "#59474f"
bright_foreground = "#1f1118"

hyprland_active_border = "rgba(ad4d66ee) rgba(5a758eee) 45deg"
hyprland_inactive_border = "rgba(89757eaa)"

red = "#ac3f45"
yellow = "#8c680b"
orange = "#a35317"
green = "#477a21"
cyan = "#037b7d"
blue = "#0869a2"
magenta = "#9c447e"
brown = "#774826"

bright_red = "#9a2934"
bright_yellow = "#765600"
bright_green = "#346704"
bright_cyan = "#0e6465"
bright_blue = "#085788"
bright_magenta = "#8a306d"
