mode = "dark"

accent = "#f55969"
selection = "#581d22"
muted = "#8d6666"

background = "#1b0607"
dark_background = "#140505"
darker_background = "#0e0304"
lighter_background = "#2d1214"

foreground = "#f5dada"
dark_foreground = "#a2898a"
light_foreground = "#dec3c3"
bright_foreground = "#fef4f4"

hyprland_active_border = "rgba(f55969ee) rgba(d387c2ee) 45deg"
hyprland_inactive_border = "rgba(8d6666aa)"

red = "#e75e70"
yellow = "#efcc83"
orange = "#f5965e"
green = "#93c69d"
cyan = "#a3dde0"
blue = "#84afdc"
magenta = "#f080b8"
brown = "#865634"

bright_red = "#f2808b"
bright_yellow = "#fee5b1"
bright_green = "#b0dab7"
bright_cyan = "#c2f2f4"
bright_blue = "#a1c5ea"
bright_magenta = "#fd9fcc"
