mode = "dark"

accent = "#1dc7b0"
selection = "#083e36"
muted = "#537b72"

background = "#000906"
dark_background = "#000705"
darker_background = "#000503"
lighter_background = "#001813"

foreground = "#cde8e2"
dark_foreground = "#7f938e"
light_foreground = "#b6d1cb"
bright_foreground = "#f0f9f7"

hyprland_active_border = "rgba(1dc7b0ee) rgba(c49e60ee) 45deg"
hyprland_inactive_border = "rgba(537b72aa)"

red = "#df7f78"
yellow = "#eacf83"
orange = "#eca56f"
green = "#56d298"
cyan = "#41e8ca"
blue = "#51b3d0"
magenta = "#d29ccc"
brown = "#865634"

bright_red = "#ec9b94"
bright_yellow = "#fde6a9"
bright_green = "#86e5b4"
bright_cyan = "#83fbe1"
bright_blue = "#7cc7df"
bright_magenta = "#e3b6de"
