mode = "dark"

accent = "#17bdef"
selection = "#063c51"
muted = "#547787"

background = "#000a14"
dark_background = "#00080f"
darker_background = "#00050a"
lighter_background = "#001924"

foreground = "#cee6f1"
dark_foreground = "#80929d"
light_foreground = "#b7cfda"
bright_foreground = "#f0f8fc"

hyprland_active_border = "rgba(17bdefee) rgba(3eb8c2ee) 45deg"
hyprland_inactive_border = "rgba(547787aa)"

red = "#ec817b"
yellow = "#e9c358"
orange = "#f59f5c"
green = "#86c573"
cyan = "#22cfdd"
blue = "#29b9f7"
magenta = "#e089c5"
brown = "#865634"

bright_red = "#f89f98"
bright_yellow = "#fbdb88"
bright_green = "#a5d895"
bright_cyan = "#70e2ed"
bright_blue = "#70ceff"
bright_magenta = "#efa6d7"
