mode = "dark"

accent = "#f29677"
selection = "#56342a"
muted = "#826c67"

background = "#190e0c"
dark_background = "#130b09"
darker_background = "#0d0706"
lighter_background = "#291c19"

foreground = "#eeddd9"
dark_foreground = "#9d8e8b"
light_foreground = "#d8c6c2"
bright_foreground = "#fdf4f3"

hyprland_active_border = "rgba(f29677ee) rgba(88a8c8ee) 45deg"
hyprland_inactive_border = "rgba(826c67aa)"

red = "#e17363"
yellow = "#fac871"
orange = "#f39c5f"
green = "#a7c28c"
cyan = "#abdbde"
blue = "#d59c7d"
magenta = "#ed9aa0"
brown = "#865634"

bright_red = "#ed9182"
bright_yellow = "#fee4b8"
bright_green = "#c0d7aa"
bright_cyan = "#c9f0f2"
bright_blue = "#e5b59b"
bright_magenta = "#fcb5ba"
