mode = "dark"

accent = "#fe9e51"
selection = "#563217"
muted = "#836d58"

background = "#140800"
dark_background = "#0f0600"
darker_background = "#0a0400"
lighter_background = "#241506"

foreground = "#eedecf"
dark_foreground = "#9b8d80"
light_foreground = "#d8c7b7"
bright_foreground = "#fcf6f0"

hyprland_active_border = "rgba(fe9e51ee) rgba(e38781ee) 45deg"
hyprland_inactive_border = "rgba(836d58aa)"

red = "#ec817f"
yellow = "#ffb670"
orange = "#fa9a73"
green = "#96c172"
cyan = "#4bcece"
blue = "#63b4ea"
magenta = "#e08bbf"
brown = "#865634"

bright_red = "#f99f9b"
bright_yellow = "#fed6b1"
bright_green = "#b1d595"
bright_cyan = "#80e1e1"
bright_blue = "#89c9f7"
bright_magenta = "#efa7d2"
