mode = "light"

accent = "#7e6b40"
selection = "#dad3c2"
muted = "#7f786a"

background = "#f4f0e7"
dark_background = "#ebe6db"
darker_background = "#ded9ce"
lighter_background = "#e4ded2"

foreground = "#342d20"
dark_foreground = "#696255"
light_foreground = "#534c3f"
bright_foreground = "#1a150b"

hyprland_active_border = "rgba(7e6b40ee) rgba(3e77a3ee) 45deg"
hyprland_inactive_border = "rgba(7f786aaa)"

red = "#9e4d4a"
yellow = "#8a6705"
orange = "#9a5826"
green = "#4c783b"
cyan = "#0e797b"
blue = "#226998"
magenta = "#924e78"
brown = "#774826"

bright_red = "#8c3a39"
bright_yellow = "#745500"
bright_green = "#386526"
bright_cyan = "#0b6466"
bright_blue = "#005887"
bright_magenta = "#803c67"
