mode = "dark"

accent = "#b381f5"
selection = "#3b2856"
muted = "#776b8a"

background = "#0d0518"
dark_background = "#0a0412"
darker_background = "#07030c"
lighter_background = "#1b1129"

foreground = "#e5ddf2"
dark_foreground = "#938b9f"
light_foreground = "#cec6db"
bright_foreground = "#f8f5fd"

hyprland_active_border = "rgba(b381f5ee) rgba(bf9f6aee) 45deg"
hyprland_inactive_border = "rgba(776b8aaa)"

red = "#d87da2"
yellow = "#efcc83"
orange = "#f39e81"
green = "#93c69d"
cyan = "#aeccfc"
blue = "#9d98f2"
magenta = "#ca9bfe"
brown = "#865634"

bright_red = "#e699b7"
bright_yellow = "#fee5b1"
bright_green = "#b0dab7"
bright_cyan = "#d2e2fd"
bright_blue = "#b3b1fd"
bright_magenta = "#d9bbfe"
