mode = "dark"

accent = "#fe8595"
selection = "#5e2e35"
muted = "#8b696d"

background = "#200c10"
dark_background = "#18090c"
darker_background = "#100608"
lighter_background = "#311a1e"

foreground = "#f4dadd"
dark_foreground = "#a38c8f"
light_foreground = "#ddc3c6"
bright_foreground = "#fdf4f5"

hyprland_active_border = "rgba(fe8595ee) rgba(bba077ee) 45deg"
hyprland_inactive_border = "rgba(8b696daa)"

red = "#e07084"
yellow = "#f6d389"
orange = "#f69f72"
green = "#93c69d"
cyan = "#a3dde0"
blue = "#84afdc"
magenta = "#f18db5"
brown = "#865634"

bright_red = "#ec8f9d"
bright_yellow = "#ffedc8"
bright_green = "#b0dab7"
bright_cyan = "#c2f2f4"
bright_blue = "#a1c5ea"
bright_magenta = "#ffaacb"
