mode = "light"

accent = "#9e6134"
selection = "#ead1c2"
muted = "#8a776e"

background = "#fff1ea"
dark_background = "#f7e6de"
darker_background = "#ead9d0"
lighter_background = "#f0ddd4"

foreground = "#3b2921"
dark_foreground = "#715f56"
light_foreground = "#5a4940"
bright_foreground = "#1f120c"

hyprland_active_border = "rgba(9e6134ee) rgba(507791ee) 45deg"
hyprland_inactive_border = "rgba(8a776eaa)"

red = "#9d4e41"
yellow = "#8d6a0d"
orange = "#9a5a23"
green = "#5a783a"
cyan = "#0d7c79"
blue = "#286993"
magenta = "#924f75"
brown = "#774826"

bright_red = "#8b3b2e"
bright_yellow = "#755701"
bright_green = "#476524"
bright_cyan = "#0c6765"
bright_blue = "#0c5882"
bright_magenta = "#803d64"
