mode = "light"

accent = "#0a7a9a"
selection = "#bcdde8"
muted = "#69818d"

background = "#eef9fe"
dark_background = "#dbf1fc"
darker_background = "#cce4f0"
lighter_background = "#cfe9f6"

foreground = "#19313c"
dark_foreground = "#526771"
light_foreground = "#3a515c"
bright_foreground = "#061921"

hyprland_active_border = "rgba(0a7a9aee) rgba(278178ee) 45deg"
hyprland_inactive_border = "rgba(69818daa)"

red = "#a54747"
yellow = "#8c6d07"
orange = "#a0581c"
green = "#467f36"
cyan = "#077f7b"
blue = "#0b6d8f"
magenta = "#98487c"
brown = "#774826"

bright_red = "#933335"
bright_yellow = "#765b00"
bright_green = "#2f6b1d"
bright_cyan = "#026a67"
bright_blue = "#055b79"
bright_magenta = "#86356b"
