mode = "light"

accent = "#1f7f72"
selection = "#bee0da"
muted = "#6b817c"

background = "#ebfbf7"
dark_background = "#dff2ed"
darker_background = "#d0e5e0"
lighter_background = "#d4eae5"

foreground = "#1c332e"
dark_foreground = "#536964"
light_foreground = "#3d524e"
bright_foreground = "#081a16"

hyprland_active_border = "rgba(1f7f72ee) rgba(955890ee) 45deg"
hyprland_inactive_border = "rgba(6b817caa)"

red = "#9e4d4a"
yellow = "#8e6c0f"
orange = "#9d5a28"
green = "#537c3b"
cyan = "#0b8076"
blue = "#29689a"
magenta = "#8e4f82"
brown = "#774826"

bright_red = "#8c3a38"
bright_yellow = "#785a07"
bright_green = "#406926"
bright_cyan = "#046a61"
bright_blue = "#0f568a"
bright_magenta = "#7d3d71"
